### ISSUE TITLE
Query for null reference produces NPE

### ISSUE THREAD

**Issue by larslorenzen** [mongodb/morphia#1033]
Hi,
i'm currently trying to migrate our application from a very old version of morphia (google code) to the current one (1.2.1).
We have many places in our application where we query for references with null values.
In the old version that just worked. In the current version it produces a NullPointerException.

example code:
```
public class QueryForNullTest {

    public static void main(String[] args) {
        MongoClient client = new MongoClient("localhost");
        Morphia morphia = new Morphia();

        Datastore datastore = morphia.createDatastore(client, "test");

        Query<Promotion> query = datastore.find(Promotion.class);
        query.field("user").equal(null);
        for (Promotion promotion : query) {
            System.out.println(promotion.user);
        }
    }

    @Entity("users")
    public static class User {
        @Id
        private ObjectId id;

        private String name;
    }

    @Entity("promotions")
    public static class Promotion {

        @Id
        private ObjectId id;

        @Reference
        private User user;
    }
}
```

Produced exception:
```
SEVERE: Error converting value(null) to reference.
java.lang.NullPointerException
  at org.mongodb.morphia.mapping.Mapper.getKey(Mapper.java:363)
  at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:593)
  at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:63)
  at org.mongodb.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:294)
  at org.mongodb.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:290)
  at org.mongodb.morphia.query.FieldEndImpl.equal(FieldEndImpl.java:85)
  at org.mongodb.morphia.query.FieldEndImpl.equal(FieldEndImpl.java:25)
  at de.dreamit.persistence.QueryForNullTest.main(QueryForNullTest.java:25)
```

**Comment by cstrempfer** [comment]
I can reproduce this with version 1.2.1, but not with the current master (1.3.0-SNAPSHOT). There is an additonal null-check in `org.mongodb.morphia.mapping.Mapper.toMongoObject(MappedField, MappedClass, Object)`, which handles your use case.

**Comment by evanchooly** [comment]
confirmed this works in master

**Comment by larslorenzen** [comment]
Yes it works in 1.3.0 but spams the log file because it produces an exception which is then caught and logged

```
java.lang.NullPointerException
  at org.mongodb.morphia.mapping.Mapper.getKey(Mapper.java:363)
  at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:593)
  at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:63)
  at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:31)
  at org.mongodb.morphia.query.QueryImpl.filter(QueryImpl.java:334)
```

```
    @Test
    public void queryForNullTest() {
        Query<C> query = getDatastore().createQuery(C.class);
        query.filter("a", null);
    }


    @Entity("as")
    public static class A {
        @Id
        protected ObjectId id;
    }

    @Entity("cs")
    public static class C {
        @Id
        protected ObjectId id;

        @Reference
        private A a;
    }
```
