### ISSUE TITLE
Can't use className as embeded field

### ISSUE THREAD

**Issue by waally** [mongodb/morphia#1088]
I use className as a embedded field. like this:
``` java
@Entity
public class MyExceptionInfo{
  @Id
  private ObjectId id;

  private String exceptionName;

  @embedded
  private List<Stack> stacks;

  public static class Stack{

    private String className;

    private String methodName;

    private int lineNo;

  }

}
```
when I query from mongodb,Appear the following error：
···
java.lang.ClassNotFoundException: 
com.waally.test.morphia.processor.impl.TestExceptionImpl
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.mongodb.morphia.mapping.DefaultCreator.getClass(DefaultCreator.java:175)
	at org.mongodb.morphia.mapping.DefaultCreator.createInstance(DefaultCreator.java:97)
	at org.mongodb.morphia.mapping.EmbeddedMapper.readMapOrCollectionOrEntity(EmbeddedMapper.java:205)
	at org.mongodb.morphia.mapping.EmbeddedMapper.readCollection(EmbeddedMapper.java:142)
	at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:45)
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:797)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:250)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:191)
	at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:134)
	at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:146)
	at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:117)
	at org.mongodb.morphia.query.QueryImpl.asList(QueryImpl.java:150)
···

**Comment by evanchooly** [comment]
You'll need to map that field to a different document name using `@Property`.  `className` is used internally by morphia to handle polymorphism.  If you have any further questions, please don't hesitate to ask on the [mailing list](https://groups.google.com/forum/#!forum/morphia).
