### ISSUE TITLE
BigDecimal on save - error

### ISSUE THREAD

**Issue by fa-at-pulsit** [mongodb/morphia#1146]
* morphia 1.3.1
* mongodb 3.4.1

On object save I get an error.
It's occurred only with objects contains BigDecimal values

```
import java.math.BigDecimal;
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;

@Entity
public class TestEntityBigDecimal {
	@Id
	private ObjectId id;
	private BigDecimal amount;
	private String code;
	
	public ObjectId getObjectId(){
		return id;
	}
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
}
```
```
import java.math.BigDecimal;
import java.net.UnknownHostException;
import org.mongodb.morphia.Datastore;
import org.mongodb.morphia.Morphia;
import com.mongodb.MongoClient;

public class TestBigDecimal {
	public static void main(String[] args) throws UnknownHostException {
		TestBigDecimal t = new TestBigDecimal();
		t.go();
	}
	
	public void go() throws UnknownHostException{
		MongoClient mongo = new MongoClient("localhost");
		Morphia morphia = new Morphia();
		morphia.map(TestEntityBigDecimal.class);
		
		Datastore dsDB1 = morphia.createDatastore(mongo, "testBigDecimal");

		TestEntityBigDecimal test = new TestEntityBigDecimal();
		test.setAmount(new BigDecimal("100.00"));
		test.setCode("ABC");
		dsDB1.save(test);
	}
}
```

```
Jan 31, 2017 2:25:05 PM org.slf4j.impl.JCLLoggerAdapter info
INFORMATION: Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
Jan 31, 2017 2:25:05 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFORMATION: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
Jan 31, 2017 2:25:05 PM org.slf4j.impl.JCLLoggerAdapter info
INFORMATION: Opened connection [connectionId{localValue:1, serverValue:57}] to localhost:27017
Jan 31, 2017 2:25:05 PM org.slf4j.impl.JCLLoggerAdapter info
INFORMATION: Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 1]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=866592}
Jan 31, 2017 2:25:05 PM org.slf4j.impl.JCLLoggerAdapter info
INFORMATION: Opened connection [connectionId{localValue:2, serverValue:58}] to localhost:27017
Jan 31, 2017 2:25:05 PM org.slf4j.impl.JCLLoggerAdapter warn
WARNUNG: Got socket exception on connection [connectionId{localValue:2, serverValue:58}] to localhost:27017. All connections to localhost:27017 will be closed.
Jan 31, 2017 2:25:05 PM org.slf4j.impl.JCLLoggerAdapter info
INFORMATION: Closed connection [connectionId{localValue:2, serverValue:58}] to localhost:27017 because there was a socket exception raised by this connection.
Exception in thread "main" com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:494)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:224)
	at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:96)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:440)
	at com.mongodb.connection.WriteCommandProtocol.receiveMessage(WriteCommandProtocol.java:262)
	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:104)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:118)
	at com.mongodb.operation.InsertOperation.executeCommandProtocol(InsertOperation.java:76)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:139)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60)
	at com.mongodb.Mongo.execute(Mongo.java:845)
	at com.mongodb.Mongo$2.execute(Mongo.java:828)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342)
	at com.mongodb.DBCollection.insert(DBCollection.java:337)
	at com.mongodb.DBCollection.insert(DBCollection.java:328)
	at org.mongodb.morphia.DatastoreImpl.saveDocument(DatastoreImpl.java:1297)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1289)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:775)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:758)
	at sandbox.TestBigDecimal.go(TestBigDecimal.java:25)
	at sandbox.TestBigDecimal.main(TestBigDecimal.java:12)

```

**Comment by jyemin** [comment]
I suspect this is due to https://jira.mongodb.org/browse/SERVER-27317.  Did you upgrade an existing server from 3.2 to 3.4?

**Comment by fa-at-pulsit** [comment]
indeed! thanks!

quick fix - 
```
use admin
db.runCommand(
{setFeatureCompatibilityVersion: "3.4"}
)
```
issue closed
