### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by McPringle** [mongodb/morphia#1173]
Username and password can be passed to the `MongoClient` constructor. The `MongoClient` instance has to be passed to the `morphia.createDatastore(mongoClient, dbName)` method. To be able to call this method, an instance of `Morphia` has to be created, which fails with an authentication error **before** being able to provide the `MongoClient` instance containing the credentials.

### Code
```java
final List<ServerAddress> seeds = new ArrayList<>();
seeds.add(new ServerAddress(dbHost, dbPort));
final List<MongoCredential> credentials = new ArrayList<>();
credentials.add(
        MongoCredential.createMongoCRCredential(
                dbUsername,
                dbName,
                dbPassword.toCharArray()
        )
);

final MongoClient mongoClient = new MongoClient(seeds, credentials); // create MongoClient with credentials

final Morphia morphia = new Morphia();  // exception authenticating: auth failed
morphia.mapPackage("XXXXXXXXXX");

datastore = morphia.createDatastore(mongoClient, dbName); // pass MongoClient with credentials
datastore.ensureIndexes();
```

### Exception
```
[2017-06-05T19:17:16.814+0200] [] [INFO] [] [org.mongodb.driver.cluster] [tid: _ThreadID=81 _ThreadName=cluster-ClusterId{value='59359212475bd84d21ef78ca', description='null'}-127.0.0.1:27017] [timeMillis: 1496683036814] [levelValue: 800] [[
  Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoSecurityException: Exception authenticating
	at com.mongodb.connection.NativeAuthenticator.authenticate(NativeAuthenticator.java:48)
	at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:109)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:46)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:116)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'auth failed' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18, "codeName" : "AuthenticationFailed" }
	at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:170)
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
	at com.mongodb.connection.NativeAuthenticator.authenticate(NativeAuthenticator.java:46)
	... 5 more
]]
```

I was not able to find any information in your documentation about connecting to MongoDB with authentication.

**Comment by jyemin** [comment]
I don't think that's what's happening.  The log message you pasted is from a background thread started by the MongoClient constructor, and is indicating that the credentials provided to that constructor are incorrect.   The Morphia constructor is not responsible.

**Comment by McPringle** [comment]
Well, the exact same credentials work fine when I connect using the command line client…

**Comment by evanchooly** [comment]
try connecting using just `MongoClient` and see what you get.
