### ISSUE TITLE
BigDecimal data type is not support [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#411]
This is [Issue 411](http://code.google.com/p/morphia/issues/detail?id=411) moved from a Google Code project.
Added by 2012-06-11T10:54:30.000Z by [atang.su...@gmail.com](http://code.google.com/u/108459479020168265364/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

    Using BigDecimal throws the following exception:
    
    com.google.code.morphia.mapping.MappingException: Could not map entity from DBObject
    	at com.google.code.morphia.Morphia.fromDBObject(Morphia.java:129)
    	at com.google.code.morphia.Morphia.fromDBObject(Morphia.java:119)
    	at id.co.bippo.commerce.dao.BookingDao.getBookCountByPersonId(BookingDao.java:143)
    	at id.co.bippo.commerce.dao.BookingDaoTest.countDetailBooking(BookingDaoTest.java:165)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    	at org.jboss.arquillian.junit.Arquillian$6$1.invoke(Arquillian.java:270)
    	at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:90)
    	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
    	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
    	at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:53)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:90)
    	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
    	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:129)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:90)
    	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:89)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:90)
    	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:75)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:90)
    	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:60)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:616)
    	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:90)
    	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:111)
    	at org.jboss.arquillian.junit.Arquillian$6.evaluate(Arquillian.java:263)
    	at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:226)
    	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:314)
    	at org.jboss.arquillian.junit.Arquillian.access$100(Arquillian.java:46)
    	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:240)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:185)
    	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:314)
    	at org.jboss.arquillian.junit.Arquillian.access$100(Arquillian.java:46)
    	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:199)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:147)
    	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Double cannot be cast to com.mongodb.DBObject
    	at com.google.code.morphia.mapping.Mapper.fromDb(Mapper.java:483)
    	at com.google.code.morphia.mapping.Mapper.fromDBObject(Mapper.java:267)
    	at com.google.code.morphia.Morphia.fromDBObject(Morphia.java:127)
    	... 86 more
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Double cannot be cast to com.mongodb.DBObject
    	at com.google.code.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:146)
    	at com.google.code.morphia.mapping.Mapper.readMappedField(Mapper.java:499)
    	at com.google.code.morphia.mapping.Mapper.fromDb(Mapper.java:480)
    	... 88 more
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Double cannot be cast to com.mongodb.DBObject
    	at com.google.code.morphia.mapping.Mapper.fromDb(Mapper.java:483)
    	at com.google.code.morphia.mapping.EmbeddedMapper.readMapOrCollectionOrEntity(EmbeddedMapper.java:231)
    	at com.google.code.morphia.mapping.EmbeddedMapper.readCollection(EmbeddedMapper.java:175)
    	at com.google.code.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:119)
    	... 90 more
    Caused by: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Double cannot be cast to com.mongodb.DBObject
    	at com.google.code.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:146)
    	at com.google.code.morphia.mapping.Mapper.readMappedField(Mapper.java:503)
    	at com.google.code.morphia.mapping.Mapper.fromDb(Mapper.java:480)
    	... 93 more
    Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.mongodb.DBObject
    	at com.google.code.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:136)
    	... 95 more

**Comment by fabioebner** [comment]
this problem has been solved?

**Comment by vchaitankar** [comment]
I am able to store a BigInteger as
{
        "signum" : -1,
        "mag" : [25165823, -1, -33731584, 31554775],
        "bitCount" : 0,
        "bitLength" : 0,
        "lowestSetBit" : 0,
        "firstNonzeroIntNum" : 0
}

I am getting mapping exceptions when I try to read data. Also I am not sure what the approach should be. I need to perform range queries on the stored big integers. Storing them as String doesnt really help me. Also I am not sure if I am storing it correctly.

**Comment by dalmat36** [comment]
I was able to store a BigDecimal however was not able to query it back from Mongo. I found this solution from http://www.technology-ebay.de/the-teams/mobile-de/blog/mapping-bigdecimals-with-morphia-for-mongodb.html that seems to work. 

```
public class BigDecimalConverter extends TypeConverter implements SimpleValueConverter {
 
    public BigDecimalConverter() {
        super(BigDecimal.class);
    }
 
    @Override
    public Object encode(Object value, MappedField optionalExtraInfo) {
        if (value == null) {
            return null;
        }
        BigDecimal bigDecimalValue = (BigDecimal) value;
 
        if (bigDecimalValue.scale() > 18) {
            bigDecimalValue = bigDecimalValue.setScale(18, BigDecimal.ROUND_DOWN);
        }
 
        DBObject dbo = new BasicDBObject();
 
        dbo.put("unscaled", bigDecimalValue.unscaledValue().longValue());
        dbo.put("scale", bigDecimalValue.scale());
 
        return dbo;
    }
 
    @Override
    @SuppressWarnings("rawtypes")
    public Object decode(Class targetClass, Object fromDBObject, MappedField field) throws MappingException {
        DBObject dbo = (DBObject) fromDBObject;
        if (dbo == null) {
            return null;
        }
 
        BigDecimal bigDecimal = null;
 
        Long unscaled = (Long) dbo.get("unscaled");
        Integer scale = (Integer) dbo.get("scale");
 
        if (unscaled != null && scale != null) {
            bigDecimal = new BigDecimal(new BigInteger(unscaled.toString()), scale);
        }
 
        return bigDecimal;
    }
 
}
```

**Comment by privatejava** [comment]
Works good after adding converter 

morphia.getMapper().getConverters().addConverter(BigDecimalConverter.class);

**Comment by evanchooly** [comment]
When the server support Decimal128, we can rely on the driver codecs to get us there.

**Comment by evanchooly** [comment]
Will require driver 3.3+

**Comment by evanchooly** [comment]
[JAVA-2140](https://jira.mongodb.org/browse/JAVA-2140)
