### ISSUE TITLE
Morphia ensureIndex fails

### ISSUE THREAD

**Issue by bpappin** [mongodb/morphia#717]
Setup: Morphia 0.110 with the required MongoDB driver 2.13.0 

I can't find any mention of why this is happening or how to fix it.
The Morphia dependency docs say that deriver 1.13.0 is a "hard" dependency.

It looks like Morphia is failing to set some sort of default parameter on the DBCollection.createIndex(...) method call.

```
[FINER|main|2:36:19]ing.MappedClass.<init> :Creating MappedClass for class pointrocket.datastore.datatype.Bookmark
[FINE|main|2:36:19]ing.MappedClass.<init> :MappedClass done: MappedClass - kind:bookmark for pointrocket.datastore.datatype.Bookmark fields:[_id ( type:ObjectId, single:true); {interface org.mongodb.morphia.annotations.Id=@org.mongodb.morphia.annotations.Id()}, owner_id ( type:ObjectId, single:true); {interface org.mongodb.morphia.annotations.Indexed=@org.mongodb.morphia.annotations.Indexed(unique=false, dropDups=false, background=false, name=idx_bookmark_ownerid, expireAfterSeconds=-1, value=ASC, sparse=true), interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=owner_id, concreteClass=class java.lang.Object)}, type ( type:BookmarkType, single:true); {interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=type, concreteClass=class java.lang.Object)}, title ( type:String, single:true); {interface org.mongodb.morphia.annotations.Indexed=@org.mongodb.morphia.annotations.Indexed(unique=false, dropDups=false, background=false, name=idx_bookmark_title, expireAfterSeconds=-1, value=ASC, sparse=true), interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=title, concreteClass=class java.lang.Object)}, target_id ( type:String, single:true); {interface org.mongodb.morphia.annotations.Indexed=@org.mongodb.morphia.annotations.Indexed(unique=false, dropDups=false, background=false, name=idx_bookmark_targetid, expireAfterSeconds=-1, value=ASC, sparse=false), interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=target_id, concreteClass=class java.lang.Object)}, note ( type:String, single:true); {interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=note, concreteClass=class java.lang.Object)}, tags ( type:String, single:true); {interface org.mongodb.morphia.annotations.Indexed=@org.mongodb.morphia.annotations.Indexed(unique=false, dropDups=false, background=false, name=idx_bookmark_tags, expireAfterSeconds=-1, value=ASC, sparse=true), interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=tags, concreteClass=class java.lang.Object)}, created ( type:Date, single:true); {interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=created, concreteClass=class java.lang.Object)}, expires ( type:Date, single:true); {interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=expires, concreteClass=class java.lang.Object)}, ordinal ( type:int, single:true); {interface org.mongodb.morphia.annotations.Property=@org.mongodb.morphia.annotations.Property(value=ordinal, concreteClass=class java.lang.Object)}]

[...]

[FINE|main|2:36:19]a.DatastoreImpl.ensureIndex :Ensuring index for bookmark with keys:{ "owner_id" : 1} and opts:{ "name" : "idx_bookmark_ownerid" , "background" : true , "sparse" : true}
com.mongodb.WriteConcernException: { "serverUsed" : "localhost/127.0.0.1:27017" , "err" : "invalid ns to index" , "code" : 10096 , "n" : 0 , "connectionId" : 65 , "ok" : 1.0}
	at com.mongodb.CommandResult.getException(CommandResult.java:77)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:110)
	at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:102)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:142)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:115)
	at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:248)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:340)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at org.mongodb.morphia.DatastoreImpl.ensureIndex(DatastoreImpl.java:297)
	at org.mongodb.morphia.DatastoreImpl.processEmbeddedAnnotations(DatastoreImpl.java:346)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:326)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:307)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:302)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:408)
	at pointrocket.datastore.dio.DioManager.getMorphiaDatastore(DioManager.java:287)
...
```

**Comment by bpappin** [comment]
If i remove the name parameter for the indexed annotations, I get this error. Looks like it maybe the same issue.

```
[FINE|main|3:19:55]a.DatastoreImpl.ensureIndex :Ensuring index for bookmark with keys:{ "owner_id" : 1} and opts:{ "background" : true , "sparse" : true}
com.mongodb.WriteConcernException: { "serverUsed" : "localhost/127.0.0.1:27017" , "err" : "no index name specified" , "code" : 12523 , "n" : 0 , "connectionId" : 68 , "ok" : 1.0}
	at com.mongodb.CommandResult.getException(CommandResult.java:77)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:110)
	at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:102)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:142)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:115)
	at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:248)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:340)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:485)
	at org.mongodb.morphia.DatastoreImpl.ensureIndex(DatastoreImpl.java:297)
	at org.mongodb.morphia.DatastoreImpl.processEmbeddedAnnotations(DatastoreImpl.java:346)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:326)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:307)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:302)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:408)
	at pointrocket.datastore.dio.DioManager.getMorphiaDatastore(DioManager.java:287)
```

**Comment by bpappin** [comment]
This turned out to be a dependency issue with an older version of the mongoldb java driver sneaking in through another source.
