### ISSUE TITLE
Optional GeoJSON fields

### ISSUE THREAD

**Issue by dgutzeit** [mongodb/morphia#722]
I am trying to use the new GeoJSON support of 0.110 version.
I have objects with some Point fields inside, but those are optional.
Morphia fails however when it tries to map a Point which is set to null. My understanding is that Morphia does not serialise null/empty fields.

Caused by: org.mongodb.morphia.mapping.MappingException: Error mapping field:yyy.User.lastKnownLocation
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:546)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:526)
	at org.mongodb.morphia.mapping.EmbeddedMapper.writeCollection(EmbeddedMapper.java:75)
	at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:29)
	at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:637)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:544)
	... 20 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.mongodb.morphia.mapping.ValueMapper.toDBObject(ValueMapper.java:21)
	at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:633)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:544)
	... 25 more
Caused by: java.lang.NullPointerException
	at org.mongodb.morphia.geo.GeometryShapeConverter.encode(GeometryShapeConverter.java:39)
	at org.mongodb.morphia.converters.DefaultConverters.toDBObject(DefaultConverters.java:221)
	at org.mongodb.morphia.mapping.ValueMapper.toDBObject(ValueMapper.java:19)
	... 27 more

**Comment by evanchooly** [comment]
if you attach a test case I can run, i'll see if I can resolve this for you.

**Comment by evanchooly** [comment]
I think I've been able to isolate the change.  On the one hand I hate trying to guess what the exact setup is, but on the other there's one glaring problem that I've resolved.  Give Jenkins about 30 minutes or so to push up a snapshot build and see if it fixes things for you if you'd like.
