### ISSUE TITLE
3.0.0 java driver throws org.bson.codecs.configuration.CodecConfigurationException

### ISSUE THREAD

**Issue by marstonstudio** [mongodb/morphia#750]
I am encountering a mapping / codec exception using Morphia after performing upgrades

Mongodb 2.6.7 -> 3.0.1
Storage Engine mmapv1 -> wiredTiger
Morphia 0.110 -> 0.111
Java Driver 2.12.3 -> 3.0.0

I am able to initialize a Morphia instance and it appears to successfully map the classes

```java
MongoClientOptions mongoClientOptions = new MongoClientOptions.Builder()
    .connectionsPerHost(100)
    .threadsAllowedToBlockForConnectionMultiplier(5)
    .maxWaitTime(1000 * 60 * 2)
    .connectTimeout(1000 * 10)
    .socketTimeout(0)
    .socketKeepAlive(false)
    .readPreference(ReadPreference.primary())
    .writeConcern(WriteConcern.ACKNOWLEDGED)
    .build();

List<ServerAddress> mongoAddresses = new ArrayList<>();
for (String host : hosts) {
    mongoAddresses.add(new ServerAddress(host, port));
}

List<MongoCredential> mongoCredentials = null;
if (user != null && !user.isEmpty() && password != null && !password.isEmpty()) {
    mongoCredentials = new ArrayList<>();
    mongoCredentials.add(MongoCredential.createMongoCRCredential(user, "admin", password.toCharArray()));
}

Set<Class> classesToMap = new HashSet<Class>(Arrays.asList(
    Arrival.class,
    Identity.class
));

morphia = new Morphia(classesToMap);

MongoClient mongoClient = new MongoClient(mongoAddresses, mongoCredentials, mongoClientOptions);
mongoDatastore = morphia.createDatastore(mongoClient, database);
mongoDatastore.ensureIndexes(true);
```

But then later on when I try and save something through the datastore, I get an exception

```java

org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class com.babelcentral.services.element.identity.Identity.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:210)
	at com.mongodb.DBObjectCodec.encodeIterable(DBObjectCodec.java:269)
	at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:196)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:128)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61)
	at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:48)
	at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:27)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:99)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:112)
	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:35)
	at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:132)
	at com.mongodb.connection.BaseWriteCommandMessage.encode(BaseWriteCommandMessage.java:89)
	at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:170)
	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:73)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:66)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219)
	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:108)
	at com.mongodb.operation.InsertOperation.executeCommandProtocol(InsertOperation.java:76)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:111)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:106)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:186)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:177)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:106)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:58)
	at com.mongodb.Mongo.execute(Mongo.java:745)
	at com.mongodb.Mongo$2.execute(Mongo.java:728)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:327)
	at com.mongodb.DBCollection.insert(DBCollection.java:323)
	at com.mongodb.DBCollection.insert(DBCollection.java:314)
	at com.mongodb.DBCollection.insert(DBCollection.java:284)
	at com.mongodb.DBCollection.insert(DBCollection.java:250)
	at com.mongodb.DBCollection.insert(DBCollection.java:172)
	at com.mongodb.DBCollection.save(DBCollection.java:392)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1062)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1130)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1114)
	at com.babelcentral.services.util.MongoUtil.save(MongoUtil.java:96)
```

Is morphia fully compatible with Java Driver 3.0.0 and wiredTiger? Is there some additional configuration / registration / code change I need to register my morphia classes with the org.bson.codecs.configuration.CodecCache?

**Comment by marstonstudio** [comment]
Nevermind.

I tracked this down to some application problems on my end. As far as I can tell, Morphia 0.111 works fine on java driver 3.0.0

**Comment by sirolf2009** [comment]
`I tracked this down to some application problems on my end`
Mind to elaborate? I'm experiencing the same issue

**Comment by LightCity** [comment]
https://jira.mongodb.org/browse/JAVA-1741
