### ISSUE TITLE
ClassCastException comparing server version

### ISSUE THREAD

**Issue by andreas-fey** [mongodb/morphia#760]
When using new IBM Informix as Mongo Server (which works with mongo client, see http://www-01.ibm.com/software/data/informix/nosql.html) and using the com.mongodb.DBCollection.save() method, the follwing error occurs:

<code>
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.mongodb.ServerVersion.compareTo(ServerVersion.java:74)
	at com.mongodb.DBCollectionImpl.useWriteCommands(DBCollectionImpl.java:448)
	at com.mongodb.DBCollectionImpl.update(DBCollectionImpl.java:265)
	at com.mongodb.DBCollection.update(DBCollection.java:191)
	at com.mongodb.DBCollection.save(DBCollection.java:975)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:949)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1013)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1000)
	at com.apiomat.backend.model.core.Customer.save(Customer.java:1025)
	at com.apiomat.backend.management.Manager.start(Manager.java:140)
	at com.apiomat.backend.management.ManagementServlet.init(ManagementServlet.java:52)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5210)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5493)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
<code>

**Comment by evanchooly** [comment]
I'm going to need a test case on this...

**Comment by evanchooly** [comment]
Without a test case, I can't really investigate this one.  Please test against the latest morphia version and submit a test case if it's still failing.

**Comment by jyemin** [comment]
It just looks like IBM Informix doesn't properly report the server version in the buildInfo command.  The driver is expecting the server to return an array of integers, which you would see in the shell as:

    > db.runCommand('buildInfo').versionArray
    [ 2, 6, 7, 0 ]

**Comment by andreas-fey** [comment]
Here is what Informix responds:

> db.runCommand('buildInfo').versionArray
[ "1", "1", "1", "20140909-1716" ]

**Comment by evanchooly** [comment]
@jyemin is there anything we can do on our end?

**Comment by jyemin** [comment]
There's not really anything that Morphia can do. And the Java driver, not incorrectly, is expecting a particular response from the server, and Informix is sending something different than expected.  Andreas, I'd suggest that you open a support case with IBM and see what they have to say.  Then if you need further assistance from MongoDB, start a thread on the mongodb-user mailing list and we can try to assist.

**Comment by evanchooly** [comment]
closing as this is an Informix issue
