### ISSUE TITLE
StackOverflowError on fetch

### ISSUE THREAD

**Issue by rahimalizada** [mongodb/morphia#767]
Trying to fetch objects from database:

```javas
final Query<Item> query = datastore.find(Item.class);
query.field(Item.ID).in(ids); // approx 2000 IDs
query.retrievedFields(true, projection); // partial retrieval

final List<Item> items= new ArrayList<>();
try {
	for (final Item item: query.fetch()) {
		items.add(item);
	}
} catch (final Throwable t) {
			t.printStackTrace();
}

... or 

query.asList();
```
and recieve the following:

java.lang.StackOverflowError
	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:129)
	at org.mongodb.morphia.mapping.DefaultCreator.newInstance(DefaultCreator.java:124)
	at org.mongodb.morphia.mapping.DefaultCreator.createList(DefaultCreator.java:99)
	at org.mongodb.morphia.converters.IterableConverter.createNewCollection(IterableConverter.java:71)
	at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:43)
	at org.mongodb.morphia.converters.DefaultConverters.decode(DefaultConverters.java:237)
	at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:58)
	at org.mongodb.morphia.converters.DefaultConverters.decode(DefaultConverters.java:237)
	at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:58)
	at org.mongodb.morphia.converters.DefaultConverters.decode(DefaultConverters.java:237)
	at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:58)
	at org.mongodb.morphia.converters.DefaultConverters.decode(DefaultConverters.java:237)
	... the same goes on for 1000+ lines
	at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:58)
	at org.mongodb.morphia.converters.DefaultConverters.decode(DefaultConverters.java:237)

Morphia version 0.111, Driver 3.0.0

No issue when reading data directly, without morphia.

**Comment by evanchooly** [comment]
Can you try again with 1.0.0-rc0?

**Comment by rahimalizada** [comment]
1.0.0-rc0 and driver 3.0.1 does not have this issue.
Thanks.
