### ISSUE TITLE
MappedField not support HashMap

### ISSUE THREAD

**Issue by ywengineer** [mongodb/morphia#772]
below is data structure:
{
	"_id" : 13010001,
	"evolutionMaterialArray" : [
		{
			"13020004" : "equip.level"
		},
		{
			"13020004" : "2*equip.level"
		},
		{
			"13020004" : "3*equip.level"
		},
		{
			"13020004" : "4*equip.level"
		}
	],
}

and the Java Object define as 
public class EquipDef {
    @Id
    private int id;
    private List<Map<Integer, String>> evolutionMaterialArray;

    ..........
}

so,  it will throw an exception when read data.

Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:199)
	at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:117)
	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:95)
	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:214)
	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:145)
	at org.mongodb.morphia.mapping.Mapper.getMappedClass(Mapper.java:239)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:606)
	at org.mongodb.morphia.mapping.EmbeddedMapper.readMapOrCollectionOrEntity(EmbeddedMapper.java:272)
	at org.mongodb.morphia.mapping.EmbeddedMapper.readCollection(EmbeddedMapper.java:210)
	at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:144)
	... 57 more

**Comment by evanchooly** [comment]
There's not enough here to recreate the problem.  Can you post a full test case?  What version are you using?  Please make sure it's 1.0.0-rc0 as there have been a lot of bug fixes in this area lately.
