### ISSUE TITLE
no className inserted when update (add)

### ISSUE THREAD

**Issue by brianwoo** [mongodb/morphia#800]
I have an entity called UserMailbox which contains an embedded Set<Event>.  Event is extended by another class named CalendarEvent.

I am able to use the DataStore.save() to save UserMailbox which contains a CalendarEvent object.  The className is also stored correctly (as below).  However, when I perform an update (add another CalendarEvent to UserMailbox), it seems that the className of the CalendarEvent is missing when the object is inserted into the DB.  Because of that, when I fetch the event, I am not able to cast the Event to a CalendarEvent.

Here is my code to demonstrate the issue:

```java
@Embedded 
public class Event implements Serializable
{
	private static final long serialVersionUID = 5384773209646208263L;
	 
	@Property
	private String eventId;
 	
	public Event() {}
	
	@Override
	public boolean equals(Object obj)
	{
		if (obj instanceof Event)
		{
			Event obj2 = (Event) obj;
			
			if (this.eventId.equals(obj2.eventId))
				return true;
		}
		
		return false;
	}
	 
	@Override
	public int hashCode()
	{
		return eventId.hashCode();
	}
}

@Embedded
public class CalendarEvent extends Event implements Serializable
{

	private static final long serialVersionUID = -1633798850487038497L;

	@Property
	private String desc;
	
	@Property
	private String location;
	
	public CalendarEvent() {}

}


@Entity(value="usermailbox")
public class UserMailbox implements Serializable
{

	private static final long serialVersionUID = 9162665160739715829L;

	@Id
	private ObjectId id;
	
	@Property
	@Indexed(unique = true)
	private String email;
		
	@Embedded
	private Set<Event> events; 
	
	public UserMailbox() {}
	
	public UserMailbox(String email) 
	{
		this.email = email;
	}

	public UserMailbox(String email, Event event)
	{
		this.email = email;
		events = new HashSet<Event>();
		events.add(event);
	}
}
```
		
Test the bug:

```java
	public void testBug()
	{
		UserMailbox userMailbox = new UserMailbox("user1");
		
		Set<Event> eventSet = new HashSet<Event>();
		CalendarEvent event = new CalendarEvent();
		event.setEventId("event1");
		event.setLocation("location1");
		eventSet.add(event);
		
		// Save mailbox with the first calendar event
		userMailbox.setEvents(eventSet);	
		ds.save(userMailbox);
		
		Query<UserMailbox> query = 
				ds.find(UserMailbox.class)
					.field("email").equal("user1");
		
		
		// create the 2nd Calendar Event and do an update 
		CalendarEvent event2 = new CalendarEvent();
		event2.setEventId("event2");
		event2.setLocation("location2");
		
		UpdateResults<UserMailbox> res =
				ds.update(
						query,
						ds.createUpdateOperations(UserMailbox.class).add(
								"events", event2, false)
					  );
		
		
		// fetch the events from the mailbox
		UserMailbox userMailbox2 = query.get();
		Set<Event> events = userMailbox2.getEvents();
		
		for (Event eachEvent : events)
		{
			CalendarEvent cEvent = (CalendarEvent) eachEvent;
			System.out.println("location = " + cEvent.getLocation());
		}
		
		// location printed: location = location1
//		java.lang.ClassCastException: com.bug.Event cannot be cast to com.bug.CalendarEvent
//		at com.bug.TestBug.testBug(TestBug.java:82)
//		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//		at java.lang.reflect.Method.invoke(Method.java:497)
//		at junit.framework.TestCase.runTest(TestCase.java:154)
//		at junit.framework.TestCase.runBare(TestCase.java:127)
//		at junit.framework.TestResult$1.protect(TestResult.java:106)
//		at junit.framework.TestResult.runProtected(TestResult.java:124)
//		at junit.framework.TestResult.run(TestResult.java:109)
//		at junit.framework.TestCase.run(TestCase.java:118)
//		at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:131)
//		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
//		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
//		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
//		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
//		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
	
	}
```

The Json:

```javascript
{
    "_id" : ObjectId("557e5ed3f059f20c7b4e166d"),
    "className" : "com.bug.UserMailbox",
    "email" : "user1",
    "events" : [ 
        {
            "className" : "com.bug.CalendarEvent",
            "location" : "location1",
            "eventId" : "event1"
        }, 
        {
            "location" : "location2",
            "eventId" : "event2"
        }
    ]
}
```

**Comment by evanchooly** [comment]
Check that you're using 1.0.0.  I just ran this test and it worked for me.

**Comment by brianwoo** [comment]
I tried it with 1.0.0 and yes, it seems that this issue was already been fixed.  Thanks very much for your help!

Brian

**Comment by evanchooly** [comment]
No problem.  Glad it works for you.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*
