### ISSUE TITLE
Morphia MappingException In List<T> After Play Framework Reload

### ISSUE THREAD

**Issue by ghw59** [mongodb/morphia#805]
Post.java:

```java
    @Reference
    public User byUser;
```

User.java:

```java
    @Embedded
    public List<Group> groups = new ArrayList<Group>(0);
```

which groups contains instances of  subclass of Group.

It works fine for the first time Play start,but after a auto-recompile (change some code) in play dev mode ,there will be an MappingException:

```
Caused by: org.mongodb.morphia.mapping.MappingException: Error setting value from converter (DoubleConverter) for models.AdminGroup.loc to [D@67c8ef50
	at org.mongodb.morphia.converters.Converters.fromDBObject(Converters.java:110) ~[morphia-1.0.0.jar:na]
	at org.mongodb.morphia.mapping.ValueMapper.fromDBObject(ValueMapper.java:27) ~[morphia-1.0.0.jar:na]
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:633) ~[morphia-1.0.0.jar:na]
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:614) ~[morphia-1.0.0.jar:na]
	at org.mongodb.morphia.mapping.EmbeddedMapper.readMapOrCollectionOrEntity(EmbeddedMapper.java:272) ~[morphia-1.0.0.jar:na]
Caused by: java.lang.IllegalArgumentException: Can not set [D field models.AdminGroup.loc to models.AdminGroup
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_45]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_45]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[na:1.8.0_45]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75) ~[na:1.8.0_45]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_45]

```

Play framework version 2.3.8/2.4.0
Morphia version 1.0.0/1.0.1

**Comment by evanchooly** [comment]
I'm looking at this one again and it's not making sense to me.  The two code snippets you've provided don't seem to be related to this stacktrace at all.  Could you please post to the [mailing list](https://groups.google.com/forum/#!forum/morphia) either a working reproduction of the problem (a link to a sample play app reproducing the problem would be awesome) or at least your AdminGroup source.
