### ISSUE TITLE
@Id annotated String causes @Reference annotated field fetch to fail.

### ISSUE THREAD

**Issue by ptwohig** [mongodb/morphia#828]
The following always causes an exception (also pasted below) in spite of the fact that both objects are present in the database.

It seems that when "Foo" is persisted with a generated ObjectId, and not a String, so when attempting to fetch the referenced object the fetch on lines 320 - 321 of ReferenceMapper.java fails to find the object.  Changing the @Id annotated field to type of ObjectId in the "Foo" class below seems to rectify this problem.

I'm not sure if I would even call this a "bug" but perhaps something that could be clarified for the @Reference annotation's documentation.  Or simply just disallow @Id annotated Strings to be auto-generated to simply avoid this confusion.

Or, maybe it's been addressed before.

```
package com.namazustudios.test;

import com.mongodb.MongoClient;
import org.bson.types.ObjectId;
import org.mongodb.morphia.AdvancedDatastore;
import org.mongodb.morphia.DatastoreImpl;
import org.mongodb.morphia.Morphia;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.annotations.Reference;
import org.mongodb.morphia.query.Query;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

/**
 * Created by patricktwohig on 7/20/15.
 */
public class TestMongo {

    private MongoClient mongoClient;

    private AdvancedDatastore advancedDatastore;

    @BeforeTest
    public void setUp() {

        final Morphia morphia = new Morphia();
        morphia.map(Foo.class, Bar.class);

        mongoClient = new MongoClient();
        advancedDatastore = new DatastoreImpl(morphia, mongoClient, "testdb");
        advancedDatastore.ensureIndexes();

    }


    @Test
    public void testReference() {

        final Foo foo = new Foo();
        advancedDatastore.insert(foo);

        final Bar bar = new Bar();
        bar.setFoo(foo);
        advancedDatastore.insert(bar);

        final Query<Bar> barQuery = advancedDatastore.createQuery(Bar.class);
        barQuery.filter("_id = ", new ObjectId(bar.getObjectId()));
        barQuery.get();

    }

    @AfterTest
    public void tearDown() {
        mongoClient.close();
    }

    @Entity(value = "foo", noClassnameStored = true)
    public static class Foo {

        @Id
        private String objectId;

        public String getObjectId() {
            return objectId;
        }

        public void setObjectId(String objectId) {
            this.objectId = objectId;
        }

    }

    @Entity(value = "bar", noClassnameStored = true)
    public static class Bar {

        @Id
        private String objectId;

        @Reference("foo")
        private Foo foo;

        public String getObjectId() {
            return objectId;
        }

        public void setObjectId(String objectId) {
            this.objectId = objectId;
        }

        public Foo getFoo() {
            return foo;
        }

        public void setFoo(Foo foo) {
            this.foo = foo;
        }

    }

}
```

```
org.mongodb.morphia.mapping.MappingException: Could not map com.namazustudios.test.TestMongo$Bar with ID: 55ae7b074d25500547ab110b
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:590)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:299)
	at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:79)
	at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:65)
	at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:60)
	at org.mongodb.morphia.query.QueryImpl.get(QueryImpl.java:402)
	at com.namazustudios.test.TestMongo.testReference(TestMongo.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
Caused by: org.mongodb.morphia.mapping.MappingException: The reference({ "$ref" : "foo", "$id" : "55ae7b074d25500547ab110a" }) could not be fetched for com.namazustudios.test.TestMongo$Bar.foo
	at org.mongodb.morphia.mapping.ReferenceMapper.resolveObject(ReferenceMapper.java:332)
	at org.mongodb.morphia.mapping.ReferenceMapper.readSingle(ReferenceMapper.java:196)
	at org.mongodb.morphia.mapping.ReferenceMapper.fromDBObject(ReferenceMapper.java:176)
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:608)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:585)
	... 31 more
```

**Comment by evanchooly** [comment]
OK.  First I apologize for taking so long.  But it turns out the "problem" is easy.  In your test, you're not assigning the value for your ID field so when the document gets saved, an _id is generated for you which is an ObjectId and not a String.  The DBRef is saved with the String version of the ObjectId and since the types don't match, reference look up fails.  If you manually assign an ID properly for your objects, this test passes.
