### ISSUE TITLE
Class Cast Exception mapping generics morphia 1.0.1 and 1.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by karpster** [mongodb/morphia#830]
1 using *0.110* and it was working.
2 not working using version *1.0.1*
3 not fixed by Cannot map entities with generic arrays #803 in *1.1.0-SNAPSHOT*

We would like to upgrade the morphia version in our project but we are blocked by the following issue:

We have a collection of Element, which has several concretizations 
(note that code is stripped, but should be enoiugh to allow reproduction)

```java
public abstract class Element <T extends Resource> {

	private T[] resources;
}

public class AudioElement extends Element <AudioResource> {

}
```
The following exception is thrown when we try to map AudioElement.

```
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:544) [morphia.jar:]
	at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:473) [morphia.jar:]
	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:95) [morphia.jar:]
	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:524) [morphia.jar:]
	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:125) [morphia.jar:]
	at org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:154) [morphia.jar:]
	at org.mongodb.morphia.Morphia.map(Morphia.java:186) [morphia.jar:]
	at X
```

**Comment by evanchooly** [comment]
I think i have a fix for you.  Could you try the jar below and let me know how it goes?

https://www.dropbox.com/s/iv9gtzhmqqz6956/morphia-1.1.0-SNAPSHOT.jar?dl=0

**Comment by karpster** [comment]
Thanks,
Will test it as soon as I can...

**Comment by evanchooly** [comment]
@karpster any update?

**Comment by fedjo** [comment]
Finally do we have a fix for this issue?

The last version that doesn't has this bug is 0.110. 
I'm currently using 1.0.1.

Thanks a lot

**Comment by fedjo** [comment]
PS: Any indications in order to fix the bug would be nice! :+1:

**Comment by evanchooly** [comment]
@fedjo did you try the snapshot build?

**Comment by fedjo** [comment]
After testing a lot I finally ended up with nothing. Nothing of my tests worked. Seems that when an Entity is parametrized with a type, the Entity cannot be mapped.

I Tested the same example as you

```java
    @Entity
	public abstract static  class Element <T extends Number> {


		@Id
		private ObjectId id;
	    private T[] resources;

		public T[] getResources() {
			return resources;
		}

		public void setResources(T[] resources) {
			this.resources = resources;
		}
	}

	@Entity
	public static class AudioElement extends Element <Long> {

		private String auelem;

		public String getAuelem() {
			return auelem;
		}

		public void setAuelem(String auelem) {
			this.auelem = auelem;
		}

	}
```

I couldn't map!

I then removed the parametrized type T defining the type explicitly like

```java
  @Entity
	public abstract static  class Element <Number> {


		@Id
		private ObjectId id;
	    private Number[] resources;

		public Number[] getResources() {
			return resources;
		}

		public void setResources(Number[] resources) {
			this.resources = resources;
		}
	}

	@Entity
	public static class AudioElement extends Element <Long> {

		private String auelem;

		public String getAuelem() {
			return auelem;
		}

		public void setAuelem(String auelem) {
			this.auelem = auelem;
		}

	}
```
Didn't work either.
The only way to map is to remove the type in generics!

The error occurs in the same file/line every time

```java
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:544)
	at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:475)
	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:95)
	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:524)
	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:125)
	at org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:154)
	at org.mongodb.morphia.Morphia.map(Morphia.java:186)
```

PS1: All tests done and all I wrote above is with assumption that Junit works fine!

Good morning and thanks
