### ISSUE TITLE
Map<String,List<String> can't save to mongodb

### ISSUE THREAD

**Issue by wiwi111** [mongodb/morphia#831]
public class UserData{
@id
String id;
public Map &lt; String, List &lt; String &gt;&gt;  data=new HashMap &lt; String, ArrayList &lt; String&gt;&gt;();
}

when I save a UserDate to mongodb ,I catched the exception 

org.mongodb.morphia.mapping.MappingException: Error mapping field:*******************
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:578)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:558)
......
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb.DBObject
	at org.mongodb.morphia.mapping.EmbeddedMapper.writeMap(EmbeddedMapper.java:118)
	at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:28)
	at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:668)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:576)
	... 29 more

**Comment by evanchooly** [comment]
Can you please post a test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia) and we'll try our best to get you sorted out.  Thanks.

**Comment by evanchooly** [comment]
I found the tests that I thought was covering this use case but they were testing something almost the same but not.  I have it fixed in master.
