### ISSUE TITLE
Lazy reference produces a MappingException

### ISSUE THREAD

**Issue by gik98** [mongodb/morphia#834]
Given this class, trying to query a document and getting the object User (or whatever object lazy referenced) produces a NullPointerException

```java
@Entity
public class Token implements DatabaseModel {
    @Id
    private ObjectId id;
    private String token;
    @Reference (lazy=true)
    private User user;
    private Date expiration;

//getters, setters, etc.....
}
```

User is just another POJO containing various fields and embedded classes.

The application runs fine avoiding lazy reference. Anyway, it would be a really nice feature to use....

All these models are put in the same package, which is mapped at startup in a Singleton, used then to build all queries, updates, and so on.

Here's the log:
```
Caused by: org.mongodb.morphia.mapping.MappingException: Could not map XX.XXXXXX.api.v1.model.Token with ID: 55d8306e7484391ee21da7f9
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:231)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:188)
	at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:131)
	at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:143)
	at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:114)
	at XX.XXXXXX.api.v1.data.DatabaseHandler.executeQuery(DatabaseHandler.java:63)
	... 32 more
Caused by: org.mongodb.morphia.mapping.MappingException: The collection 'User' is not mapped to a java class.
	at org.mongodb.morphia.mapping.Mapper.getClassFromCollection(Mapper.java:251)
	at org.mongodb.morphia.mapping.Mapper.refToKey(Mapper.java:513)
	at org.mongodb.morphia.mapping.ReferenceMapper.createOrReuseProxy(ReferenceMapper.java:86)
	at org.mongodb.morphia.mapping.ReferenceMapper.readSingle(ReferenceMapper.java:204)
	at org.mongodb.morphia.mapping.ReferenceMapper.fromDBObject(ReferenceMapper.java:43)
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:765)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:226)
	... 44 more

```

EDIT: the exception is a nullpointerexception thrown by undertow, the log is shortened for clarity

The exception (might be a bug?) is thrown using 1.0.1 and 1.1.0snap both.

Running Java EE 7 on a Wildfly 9 server.
MongoDb version 3.0.5 running on Ubuntu Server

**Comment by gik98** [comment]
For clarity

* Not a duplicate of #608 since there's no circular reference
* Classnames are stored (correctly) in database

**Comment by evanchooly** [comment]
Please post a test case that recreates this error to the [mailing list](https://groups.google.com/forum/#!forum/morphia).  Lazy references work (according to the tests).  You're likely missing a step in your scenario.

**Comment by p0thi** [comment]
@gik98 I am facing the same issue right now. DIs you find a solution for this?

**Comment by gik98** [comment]
Huh.
Really sorry @p0thi, can't give you a sure answer.
If I remember well it finally worked, but I'm not coding on that project anymore since fall 2015, can't either find the code...
