### ISSUE TITLE
ClassCastException when getting by ObjectId

### ISSUE THREAD

**Issue by frapontillo** [mongodb/morphia#852]
I have a Repository that extends from `BasicDAO<MyClass, ObjectId>`, as my `_id`s are `ObjectId`s.
How can I query to find a specific object by its `_id`? I have tried:

```java
MyClass myObject = myClassRepository.get(new ObjectId("5605851cbc1f75fc6f14d5cf"));
```

but I get the following exception, even if I use the `Query` with the `equal` method:

```
Caused by: java.lang.ClassCastException: org.bson.types.ObjectId cannot be cast to com.mongodb.DBRef
	at org.mongodb.morphia.mapping.ReferenceMapper.resolveObject(ReferenceMapper.java:251)
	at org.mongodb.morphia.mapping.ReferenceMapper.readSingle(ReferenceMapper.java:188)
	at org.mongodb.morphia.mapping.ReferenceMapper.fromDBObject(ReferenceMapper.java:174)
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:640)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:617)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:310)
	at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:87)
	at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:73)
	at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:68)
	at org.mongodb.morphia.query.QueryImpl.get(QueryImpl.java:421)
	at org.mongodb.morphia.dao.BasicDAO.findOne(BasicDAO.java:221)
```

Morphia is at latest stable 1.0.1.
MongoDB is at 3.0.4.
Mac OS X 14.5.0.
JDK 1.8.

**Comment by evanchooly** [comment]
Can you post some code to the [mailing list](https://groups.google.com/forum/#!forum/morphia)?  It's probably a model error but it's hard to say without seeing code.

**Comment by frapontillo** [comment]
I understood what my mistake was.

I am using [mongoose](http://mongoosejs.com/) on my NodeJS application, and it saves references (project in the example) with the following format:

```javascript
{
    "_id" : ObjectId("5605b7dac901fa0e7507da43"),
    "date_start" : ISODate("2015-09-25T21:08:42.334Z"),
    "project" : ObjectId("55f9b1a41b4fd3f0481899f0"),
    "__v" : 0
}
```

whereas morphia uses the following format:

```javascript
{
    "_id" : ObjectId("5605b7dac901fa0e7507da43"),
    "className" : "net.frakbot.crowdpulse.data.entity.ProjectRun",
    "date_start" : ISODate("2015-09-25T21:08:42.334Z"),
    "project" : {
        "$ref" : "Project",
        "$id" : ObjectId("55f9b1a41b4fd3f0481899f0")
    }
}
```

The main object was saved from mongoose, so morphia didn't understand how to map the `ObjectId` as a reference.

The good thing is that mongoose seems to understand the morphia-kind of relationships, but the opposite is not true.

For full reference, here are my simplified POJOs that error:

```java
public class Project {
    @Id private ObjectId id;
    @Reference private List<ProjectRun> runs;
}

public class ProjectRun {
    @Id private ObjectId id;
    private Date dateStart;
    @Reference private Project project;
}
```

**Comment by evanchooly** [comment]
If you use `@Reference(idOnly = true)` it should read that mongoose data just fine.

**Comment by frapontillo** [comment]
It works! Thank you!
