### ISSUE TITLE
Error composite custom object id

### ISSUE THREAD

**Issue by Magalanez** [mongodb/morphia#866]
Same error than https://github.com/mongodb/morphia/issues/307

java.lang.RuntimeException: @Id mismatch: model.MyClass@7025df30 != model.MyClass@41033ac0 for model.MyClassContainer
	at org.mongodb.morphia.mapping.Mapper.updateKeyInfo(Mapper.java:280)
	at org.mongodb.morphia.DatastoreImpl.postSaveOperations(DatastoreImpl.java:1237)
	at org.mongodb.morphia.DatastoreImpl.postSaveOperations(DatastoreImpl.java:1223)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1010)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1080)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1063)

Morphia version: 1.0.1

Any suggestions??

**Comment by gkgupta** [comment]
I also faced the same issue. I looked at the code throwing this error. It was calling equals function internally. Still not sure how it worked, but if you override the equals and hashcode methods of your ID class. Then this error goes away.

**Comment by evanchooly** [comment]
Yes.  you'll need a `.equals()` on your custom ID.
