### ISSUE TITLE
Reading to a List<Object> throws NPE

### ISSUE THREAD

**Issue by plaa** [mongodb/morphia#876]
I'm trying to store / retrieve generic JSON objects as Java maps and lists.  When I use:

    private Map<String, Object> jsonObject;

and MongoDB contains

	"jsonObject" : {
		"array" : [
			{
				"foo" : "bar"
			}
		]
	},

everything works fine, and I get a Map containing a List containing a Map.

Similarly, when I have a List:

    private List<Object> jsonList;

and MongoDB contains an array of primitives:

	"jsonList" : [
		1,
		"string",
		true,
		null
	],

everything works as expected.  But if the array contains an object, I get an NPE (stack trace below):

	"jsonList" : [
		{
			"foo" : "bar"
		}
	],

I'm using Morphia 1.0.1, Mongo Java driver 3.2.0 and MongoDB 2.4.14.

Stack trace:

```
java.lang.RuntimeException: java.lang.NullPointerException
        at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:173) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:638) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:595) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:56) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.converters.Converters.fromDBObject(Converters.java:106) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.ValueMapper.fromDBObject(ValueMapper.java:27) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:636) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:617) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:310) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:87) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:73) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:68) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.query.QueryImpl.get(QueryImpl.java:421) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.DatastoreImpl.get(DatastoreImpl.java:739) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.DatastoreImpl.getByKey(DatastoreImpl.java:750) ~[morphia-1.0.1.jar:na]
...
Caused by: java.lang.NullPointerException: null
        at java.lang.Class.isAssignableFrom(Native Method) ~[na:1.7.0_79]
        at org.mongodb.morphia.mapping.EmbeddedMapper.isMapOrCollection(EmbeddedMapper.java:277) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.EmbeddedMapper.readCollection(EmbeddedMapper.java:196) ~[morphia-1.0.1.jar:na]
        at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:144) ~[morphia-1.0.1.jar:na]
        ... 82 common frames omitted
```

**Comment by evanchooly** [comment]
This works on master (which is currently 1.2.0 essentially.)  Closing for now.  If you run in to something like this after updating, please post a test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia) so we can take a look.
