### ISSUE TITLE
Polymorphic Enum to string serialization leads to ClassCastException

### ISSUE THREAD

**Issue by MilusW** [mongodb/morphia#889]
### Example
```
@Entity
public class MyEntity {
    @Id
    private ObjectId id;
    @Embedded
    private MyType myType = MyEnum.INSTANCE; 
}

public interface MyType { }

public enum MyEnum {
    INSTANCE
}
```
### Description
When Morphia saves field `myType`, it will find that this is enum, so it will use `EnumConverter`, and converts its value to string. It leads to loosing information about type of field `myType`. When loading, Morphia sees that this field has `@Embedded` annotation, so it tries to load DBObject, but it was saved just as a string, so it leads to `ClassCastException`:
```
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb.DBObject

	at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:173)
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:638)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:617)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:310)
	at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:87)
	at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:73)
	at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:68)
	at org.mongodb.morphia.query.QueryImpl.get(QueryImpl.java:421)
```
### Possible solution
During writing it is possible to compare actual type and declared. If declared type is equal to actual type and it is enum, then Morphia should use simple enum->string conversion. If not, it should append class name of enum.

**Comment by evanchooly** [comment]
enums shouldn't need to be marked with `@Embedded`.  Try removing that and see if the error persists.

**Comment by evanchooly** [comment]
No response so closing for now.  We can reopen this if necessary.
