### ISSUE TITLE
How to map a field that is an arbitrarily nested document?

### ISSUE THREAD

**Issue by serge-nikitin** [mongodb/morphia#947]
I tried this:

```
@Entity
public class Test {
    @Id
    public ObjectId id;
    public Date createdAt;
    public Document data;
}
```

And inserting of such entity works fine:

```
Test t = new Test();
t.createdAt = new Date();
t.data = new Document("qwe", 12).append("wer", asList("123", "345", "dsf"));
datastore.save(t);
```
But there are two problems:
1) On the start of program there is a warm message:
```
06:33:47 [main] WARN  org.mongodb.morphia.mapping.validation.MappingValidator - MapKeyDifferentFromString complained about test.Test.data : Maps cannot be keyed by Object (Map<Object,?>); Use a parametrized type that is supported (Map<String/Enum/Long/ObjectId/..., ?>)
```
2) I can not get back such entity; `datastore.createQuery(Test.class).asList())` produce error:
```
Exception in thread "main" java.lang.ClassCastException: org.bson.Document cannot be cast to java.util.List
    at org.mongodb.morphia.mapping.DefaultCreator.createList(DefaultCreator.java:131)
    at org.mongodb.morphia.converters.IterableConverter.createNewCollection(IterableConverter.java:122)
    at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:32)
    at org.mongodb.morphia.converters.Converters.decode(Converters.java:85)
```
How do you keep an arbitrarily nested document in your Morphia entities?

**Comment by evanchooly** [comment]
Try making `data` a `Map` instead of a `Document`.  If you still have problems after that, please post to the [mailing list](https://groups.google.com/forum/#!forum/morphia) and we can discuss it.
