### ISSUE TITLE
Does morphia support android?

### ISSUE THREAD

**Issue by leisim** [mongodb/morphia#954]
Hi,

I tried using morphia on android. The app builds fine but it crashes with the exception
```
java.lang.ExceptionInInitializerError
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:309)
at java.lang.Class.forName(Class.java:273)
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.testDependencyFullFilled(LazyFeatureDependencies.java:42)
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.createDefaultProxyFactory(LazyFeatureDependencies.java:57)
at org.mongodb.morphia.mapping.Mapper.<init>(Mapper.java:100)
at org.mongodb.morphia.Morphia.<init>(Morphia.java:45)
at java.lang.Thread.run(Thread.java:818)

Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116)
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104)
at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
at java.lang.Class.classForName(Native Method) 
at java.lang.Class.forName(Class.java:309) 
at java.lang.Class.forName(Class.java:273) 
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.testDependencyFullFilled(LazyFeatureDependencies.java:42) 
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.createDefaultProxyFactory(LazyFeatureDependencies.java:57) 
at org.mongodb.morphia.mapping.Mapper.<init>(Mapper.java:100) 
at org.mongodb.morphia.Morphia.<init>(Morphia.java:45)
at java.lang.Thread.run(Thread.java:818) 

Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144) 
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116) 
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108) 
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104) 
at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69) 
at java.lang.Class.classForName(Native Method) 
at java.lang.Class.forName(Class.java:309) 
at java.lang.Class.forName(Class.java:273) 
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.testDependencyFullFilled(LazyFeatureDependencies.java:42) 
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.createDefaultProxyFactory(LazyFeatureDependencies.java:57) 
at org.mongodb.morphia.mapping.Mapper.<init>(Mapper.java:100) 
at org.mongodb.morphia.Morphia.<init>(Morphia.java:45)  
at java.lang.Thread.run(Thread.java:818) 

Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
at java.lang.ClassLoader.defineClass(ClassLoader.java:300)
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384) 
at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219) 
at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144) 
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116) 
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108) 
at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104) 
at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69) 
at java.lang.Class.classForName(Native Method) 
at java.lang.Class.forName(Class.java:309) 
at java.lang.Class.forName(Class.java:273) 
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.testDependencyFullFilled(LazyFeatureDependencies.java:42) 
at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.createDefaultProxyFactory(LazyFeatureDependencies.java:57) 
at org.mongodb.morphia.mapping.Mapper.<init>(Mapper.java:100) 
at org.mongodb.morphia.Morphia.<init>(Morphia.java:45) 
at java.lang.Thread.run(Thread.java:818) 
```

**Comment by evanchooly** [comment]
Morphia wasn't really built with Android in mind but it doesn't do anything terribly exotic outside of proxying lazy references.  Android isn't a Java Virtual Machine and may not support such proxies.  I don't know one way or another.  One possible solution to sidestep this, though, would be to exclude the cglib dependencies from your application.  This will direct morphia to not try to use those proxies and just create the referenced objects directly.  If you have any further questions please don't hesitate to ask on the [mailing list](https://groups.google.com/forum/#!forum/morphia).
